### ISSUE TITLE
R Version 4 fail

### ISSUE THREAD

**Issue by Ariel225** [ropensci/genderdata#10]
Hi,

install.packages("genderdata", repos = "http://packages.ropensci.org")

Warning in install.packages :
  package ‘genderdata’ is not available for this version of R

Any updates?

**Comment by dvmasterov** [comment]
Same issue here as well.

**Comment by timathomas** [comment]
@Ariel225 and @dvmasterov I had the same issue. My resolution was to 
1. fork and clone the repo
2. open up the `genderdata.Rproj` in Rstudio
3. install and restart the package. 

Now it works!

I tried to upload the packages into my fork to download but for some reason ran into this error: 
```
> devtools::install_github("timathomas/genderdata", type = "source")
Downloading GitHub repo timathomas/genderdata@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/timathomas/genderdata/tarball/HEAD' failed
```

Let's just say that I'm not an expert package builder, just dangerous ;)

**Comment by lmullen** [comment]
This is a duplicate issue of this: https://github.com/lmullen/gender/issues/63

That is fixed now. Please see the instructions for the gender package: https://github.com/lmullen/gender/issues
