### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by fangzhou-xie** [ropensci/genderdata#8]
<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gender_0.5.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     crayon_1.3.4     dplyr_0.8.5      assertthat_0.2.1 R6_2.4.1        
 [6] lifecycle_0.2.0  magrittr_1.5     pillar_1.4.3     rlang_0.4.6      rstudioapi_0.11 
[11] vctrs_0.2.4      ellipsis_0.3.0   tools_3.6.3      glue_1.4.0       purrr_0.3.4     
[16] compiler_3.6.3   pkgconfig_2.0.3  tidyselect_1.0.0 tibble_3.0.1 
```
</details>

```
> install.packages("genderdata", repos = "http://packages.ropensci.org")
Error in install.packages : error reading from connection
```

I am currently having trouble with installing this package. I wonder what could be the cause here?

**Comment by sckott** [comment]
weird, it works for me. not sure what might be the issue.  @jeroen any ideas for why reading from our registry might error?

**Comment by lmullen** [comment]
Has the rOpenSci package repository switched to https?

**Comment by lmullen** [comment]
@mark-fangzhou-xie If you are in a hurry and just want to get to using the package, you can run this: `remotes::install_github("ropensci/genderdata")`

**Comment by sckott** [comment]
forgot we have a new url - could try `install.packages("genderdata", repos = "https://dev.ropensci.org")`

**Comment by lmullen** [comment]
@sckott Thanks for letting me know. I didn't know the URL for the CRAN-like repository had changed. But that URL doesn't work for me. Same `error reading from connection`, which I assume means that the URL isn't there. Is that the right URL for installing packages, as opposed to checking on the status of builds?

**Comment by fangzhou-xie** [comment]
Thank you @lmullen @sckott ! Both solution (installing the development version and changing the url) work for me.

**Comment by lmullen** [comment]
@sckott Well, that URL didn't work for me 30 minutes ago, but now it does. Sorry for doubting you. 🙀 I'll update the package, which happens to be going back to CRAN for an update right now anyway.

**Comment by sckott** [comment]
sorry about the downtime, there was some down time for the infrastructure behind that earlier today, hopefully just a temporary blip
